REM-Practice_lesson_2
 

REM-1(EXECUTE)
REM OPTION D IS CORRECT

DECLARE
V_AMOUNT INTEGER(10);
BEGIN
DBMS_OUTPUT.PUT_LINE(V_AMOUNT);
END;

 


REM-2
SET SERVEROUTPUT ON;
DECLARE 
MESSAGE VARCHAR2(30) :='HELLO WORLD';
BEGIN
DBMS_OUTPUT.PUT_LINE(MESSAGE);
END;
/

 

REM-Practice_lesson_3

 
REM-1
REM VALID VARIABLES   
 

REM today               
REM last_name           
REM Isleap$year         
REM NUMBER#
REM number1to7

REM invalid variables
REM today's_date    '
REM Number_of_days_in_February_this_year
REM #number

rem-2

/*VALID DECLARATION AND IDENTIFIERS

PRINT_NAME CONSTANT VARCHAR2(10);
deliver_to VARCHAR2(10):='johnson';
by_when DATE:=CURRENT_DATE+1;
number_of_copies PLS_INTEGER; */

 

REM-3

REM THE BLOCK ECECUTES SUCCESSFULLY AND PRINTS "fernadez".
 
REM-4
SET SERVEROUTPUT ON;
DECLARE 
V_TODAY DATE := SYS_DATE;
V_TOMORROW V_TODAY%TYPE:=SYS_DATE+1;
BEGIN
DBMS_OUTPUT.PUT_LINE('HELLO WORLD');
DBMS_OUTPUT.PUT_LINE('TODAY IS : ' || V_TODAY);
DBMS_OUTPUT.PUT_LINE('TOMORROW IS : ' ||V_TOMORROW);
END;
/

 

 

REM-5 (BIND VARIABLE)

SET SERVEROUTPUT ON;
DECLARE 

    V_TODAY DATE :=CURRENT_DATE;
    V_TOMORROW V_TODAY%TYPE:=CURRENT_DATE+1;
    B_BASIC_PERCENT NUMBER :=45;
    B_PF_PERCENT NUMBER :=12;
VARIABLE BIND_BASIC NUMBER ;
VARIABLE BIND_PF NUMBER;

BEGIN
:BIND_BASIC :=B_BASIC_PERCENT;
:BIND_PF:=B_PF_PERCENT;
DBMS_OUTPUT.PUT_LINE('HELLO WORLD');
DBMS_OUTPUT.PUT_LINE('TODAY IS : ' || V_TODAY);
DBMS_OUTPUT.PUT_LINE('TOMORROW IS : ' ||V_TOMORROW);
DBMS_OUTPUT.PUT_LINE('b_basic_percent');

 

END;
/
PRINT :BIND_BASIC;
PRINT :BIND_PF;


REM-Practice_lesson_4

REM-1
--a)
    THE VALUE OF V_WEIGHT AT POSITION 1 IS: 1
--b)
    THE VALUE OF V_NEW_LOCN AT POSITION 1 IS: 'EUROPE'
--C)
    THE VALUE OF V_WEIGHR AT POSITION 2 IS: 2
--d)
    THE VALUE OF V_MESSAGE AT POSITION 2 IS: 'PRODUCT 11001 IS IN STOCK';
--e)
    THE VALUE OF V_NEW_LOCN AT POSITION 2 IS: 'WESTERN EUROPE';

REM-2

--A)
    THE VALUE OF V_CUSTOMER IN NESTED BLOCK IS: 201 & NUMBER(7)
--B)
    THE VALUE OF V_NAME IN NESTED BLOCK IS: 'Unisports' & VARCHAR2(25)
--C)
    THE VALUE OF V_CREDIT_RATING IN NESTED BLOCK IS:'GOOD' & VARCHAR2(50);
--D)
    THE VALUE OF V_CUSTOMER IN MAIN BLOCK IS: 'Womansport' & VARCHAR(50);

--E)
    THE VALUE OF V_NAME IN MAIN BLOCK IS: NO V_NAME IN MAIN BLOCK
--F)
    THE VALUE OF V_CREDIT_RATIND IN MAIN BLOCK IS:'EXCELLENT' & VARCHAR2(50);


REM-3

SET SERVEROUTPUT ON;
DECLARE 

    V_TODAY DATE :=CURRENT_DATE;
    V_TOMORROW V_TODAY%TYPE:=CURRENT_DATE+1;
    B_BASIC_PERCENT NUMBER :=45;
    B_PF_PERCENT NUMBER :=12;
--BIND VARIABLES

 

VARIABLE BIND_BASIC NUMBER ;
VARIABLE BIND_PF NUMBER;

 

BEGIN
/**ASSIGNING VALUES TO 
BIND VARIABLES */

 

:BIND_BASIC :=B_BASIC_PERCENT;
:BIND_PF:=B_PF_PERCENT;

 

V_FNAME VARCHAR2(15);
V_EMP_SAL NUMBER(10);
SELECT FIRST_NAME,SALARY INTO V_FNAME,V_EMP_SAL
    FROM EMPLOYEES
    WHERE EMPLOYEE_ID=110;

DBMS_OUTPUT.PUT_LINE('HELLO');

 

DBMS_OUTPUT.PUT_LINE('YOUR SALARY IS'|| V_EMP_SAL*( B_BASIC_PERCENT/100));
DBMS_OUTPUT.PUT_LINE('YOUR CONTRIBUTION TOWARDS PF IS : '|| V_EMP_SAL*( B_PF_PERCENT/100));

 

/*
DBMS_OUTPUT.PUT_LINE('TODAY IS : ' || V_TODAY);
DBMS_OUTPUT.PUT_LINE('TOMORROW IS : ' ||V_TOMORROW);
DBMS_OUTPUT.PUT_LINE('b_basic_percent');
*/

 

END;
/
PRINT :BIND_BASIC;
PRINT :BIND_PF;

REM-Practice_lesson_5

/** 5. USING SQL STATEMENTS WITHIN PL/SQL**/

REM-1
SET SERVEROUTPUT ON
DECLARE
V_MAX_DEPTNO NUMBER;
    BEGIN
        SELECT MAX(DEPARTMENT_ID) INTO V_MAX_DEPTNO
        FROM DEPARTMENTS;
        DBMS_OUTPUT.PUT_LINE('THE MAXIMUM DEPARTMENT IS: '||V_MAX_DEPTNO);
END;
/

REM-02
SET SERVEROUTPUT ON
DECLARE
V_MAX_DEPTNO NUMBER;
V_DEPT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE := 'EDUCATION';
V_DEPT_ID NUMBER;
V_ROWS_UPDATED VARCHAR2(30);
V_DEPT_DATA VARCHAR2(70);

BEGIN
        SELECT MAX(DEPARTMENT_ID) INTO V_MAX_DEPTNO
        FROM DEPARTMENTS;
        DBMS_OUTPUT.PUT_LINE('THE MAXIMUM DEPARTMENT IS: '||V_MAX_DEPTNO);
V_DEPT_ID:= ( V_MAX_DEPTNO + 10 );
INSERT INTO DEPARTMENTS ( DEPARTMENT_NAME, DEPARTMENT_ID)
VALUES ( V_DEPT_NAME , V_DEPT_ID);
V_ROWS_UPDATED := (SQL%ROWCOUNT || 'ROWS UPDATED');
DBMS_OUTPUT.PUT_LINE(V_ROWS_UPDATED);

 

END;
/
SELECT DEPARTMENT_ID,DEPARTMENT_NAME ,MANAGER_ID,LOCATION_ID

 

        FROM DEPARTMENTS WHERE DEPARTMENT_ID =370;

 

REM-03

SET SERVEROUTPUT ON
DECLARE
V_MAX_DEPTNO NUMBER;
V_DEPT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE := 'EDUCATION';
V_DEPT_ID NUMBER;
V_ROWS_UPDATED VARCHAR2(30);
V_DEPT_DATA VARCHAR2(70);

 

    BEGIN
        SELECT MAX(DEPARTMENT_ID) INTO V_MAX_DEPTNO
        FROM DEPARTMENTS;
        DBMS_OUTPUT.PUT_LINE('THE MAXIMUM DEPARTMENT IS: '||V_MAX_DEPTNO);
V_DEPT_ID:= ( V_MAX_DEPTNO + 10 );
UPDATE DEPARTMENTS SET LOCATION_ID =3000
        WHERE DEPARTMENT_ID = V_MAX_DEPTNO;

 

END;
/
SELECT DEPARTMENT_ID,DEPARTMENT_NAME ,MANAGER_ID,LOCATION_ID

 

        FROM DEPARTMENTS WHERE DEPARTMENT_ID =380;

DECLARE
V_MAX_DEPTID DEPARTMENTS.DEPARTMENT_ID%TYPE;
BEGIN
SELECT MAX(DEPARTMENT_ID)  INTO V_MAX_DEPTID
    FROM DEPARTMENTS;
    END;    /
