REM -- PRACTICE SESSION_08

REM --1ST QUETION (A,B,C,D ALL COMBINED)
DECLARE V_DEPTNO NUMBER :=10;

CURSOR C_EMP_CURSOR IS
SELECT LAST_NAME,SALARY,MANAGER_ID
FROM EMPLOYEES WHERE DEPARTMENT_ID=V_DEPTNO;
BEGIN
FOR EMP_RECORD IN C_EMP_CURSOR
LOOP
IF EMP_RECORD.SALARY <5000 AND (EMP_RECORD.MANAGER_ID=101 OR EMP_RECORD.MANAGER_ID=124)
THEN DBMS_OUTPUT.PUT_LINE(EMP_RECORD.LAST_NAME || 'dUE FOR A RAISE');
END IF;
END LOOP;
END;
/
DECLARE V_DEPTNO NUMBER :=20;

CURSOR C_EMP_CURSOR IS
SELECT LAST_NAME,SALARY,MANAGER_ID
FROM EMPLOYEES WHERE DEPARTMENT_ID=V_DEPTNO;
BEGIN
FOR EMP_RECORD IN C_EMP_CURSOR
LOOP
IF EMP_RECORD.SALARY <5000 AND (EMP_RECORD.MANAGER_ID=101 OR EMP_RECORD.MANAGER_ID=124)
THEN DBMS_OUTPUT.PUT_LINE(EMP_RECORD.LAST_NAME || 'dUE FOR A RAISE');
ELSE
DBMS_OUTPUT.PUT_LINE(EMP_RECORD.LAST_NAME || 'NO DUE FOR A RAISE');
END IF;
END LOOP;
END;
/
DECLARE V_DEPTNO NUMBER :=50;

CURSOR C_EMP_CURSOR IS
SELECT LAST_NAME,SALARY,MANAGER_ID
FROM EMPLOYEES WHERE DEPARTMENT_ID=V_DEPTNO;
BEGIN
FOR EMP_RECORD IN C_EMP_CURSOR
LOOP
IF EMP_RECORD.SALARY <5000 AND (EMP_RECORD.MANAGER_ID=101 OR EMP_RECORD.MANAGER_ID=124)
THEN DBMS_OUTPUT.PUT_LINE(EMP_RECORD.LAST_NAME || 'dUE FOR A RAISE');
END IF;
END LOOP;
END;
/
DECLARE V_DEPTNO NUMBER :=80;

CURSOR C_EMP_CURSOR IS
SELECT LAST_NAME,SALARY,MANAGER_ID
FROM EMPLOYEES WHERE DEPARTMENT_ID=V_DEPTNO;
BEGIN
FOR EMP_RECORD IN C_EMP_CURSOR
LOOP
IF EMP_RECORD.SALARY <500 AND (EMP_RECORD.MANAGER_ID=101 OR EMP_RECORD.MANAGER_ID=124)
THEN DBMS_OUTPUT.PUT_LINE(EMP_RECORD.LAST_NAME || 'dUE FOR A RAISE');
END IF;
END LOOP;
END;
/


REM --2ND QUESTION(A,B,C,D COMBINED)

DECLARE
CURSOR C_DEPT_CURSOR IS
SELECT DEPARTMENT_ID,DEPARTMENT_NAME
FROM DEPARTMENTS
WHERE DEPARTMENT_ID<100
ORDER BY DEPARTMENT_ID;
CURSOR C_EMP_CURSOR(V_DEPTNO NUMBER) IS
SELECT LAST_NAME,JOB_ID,HIRE_DATE,SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID=V_DEPTNO AND EMPLOYEE_ID<120;

V_CURRENT_DEPTNO DEPARTMENTS.DEPARTMENT_ID%TYPE;
V_CURRENT_DNAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
V_ENAME EMPLOYEES.LAST_NAME%TYPE;
V_JOB EMPLOYEES.JOB_ID%TYPE;
V_HIREDATE EMPLOYEES.HIRE_DATE%TYPE;
V_SAL EMPLOYEES.SALARY%TYPE;

BEGIN
OPEN C_DEPT_CURSOR;
LOOP
FETCH C_DEPT_CURSOR INTO V_CURRENT_DEPTNO,V_CURRENT_DNAME;
EXIT WHEN C_DEPT_CURSOR%NOTFOUND;
DBMS_OUTPUT.PUT_LINE('DEPARTMENT NUMBER :' || V_CURRENT_DEPTNO || 'DEPARTMENT NAME : ' || V_CURRENT_DNAME);

IF C_EMP_CURSOR%ISOPEN THEN
CLOSE C_EMP_CURSOR;
END IF;
OPEN C_EMP_CURSOR (V_CURRENT_DEPTNO);
LOOP
FETCH C_EMP_CURSOR INTO V_ENAME,V_JOB,V_HIREDATE,V_SAL;
EXIT WHEN C_EMP_CURSOR%NOTFOUND;
DBMS_OUTPUT.PUT_LINE(V_ENAME || ' '||V_JOB|| ' '||V_HIREDATE|| ' '||V_SAL);
END LOOP;
DBMS_OUTPUT.PUT_LINE('-----------------------------');
CLOSE C_EMP_CURSOR;

END LOOP;
CLOSE C_DEPT_CURSOR;
END;
/

REM -- OPTIONAL QURIEIS (8-2)

REM --1.QUESTION

CREATE TABLE TOP_SALARY(SALARY NUMBER(8,2));

REM --(2,3,4 COMBINED)

DEFINE P_NUM =1
DECLARE
NUM1  NUMBER(3) := &P_NUM;
SAL EMPLOYEES.SALARY%TYPE;
CURSOR EMP_CURSOR IS
SELECT DISTINCT SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC;
BEGIN
OPEN EMP_CURSOR;
FETCH EMP_CURSOR INTO SAL;
WHILE EMP_CURSOR%ROWCOUNT<=NUM1 AND EMP_CURSOR%FOUND
LOOP
INSERT INTO TOP_SALARY (SALARY)
VALUES(SAL);
FETCH EMP_CURSOR INTO SAL;
END LOOP;
CLOSE EMP_CURSOR;
END;
/


REM -- 5TH QUESTION
SELECT * FROM top_salary;
