REM -- 1ST QUESTION

SELECT DEPARTMENT_ID
FROM DEPARTMENTS
MINUS
SELECT DEPARTMENT_ID
FROM EMPLOYEES
WHERE JOB_ID='ST_CLERK';

REM --2ND QUESTION

SELECT COUNTRY_ID,COUNTRY_NAME
FROM COUNTRIES
MINUS
SELECT L.COUNTRY_ID,C.COUNTRY_NAME
FROM LOCATIONS L
JOIN COUNTRIES C
ON (L.COUNTRY_ID= C.COUNTRY_ID)
JOIN DEPARTMENTS D
ON(D.LOCATION_ID=L.LOCATION_ID);


REM --3RD QUESTION

SELECT DISTINCT JOB_ID ,DEPARTMENT_ID,TO_CHAR('X') AS "DUMMY"
FROM EMPLOYEES
WHERE DEPARTMENT_ID=10
UNION ALL
SELECT DISTINCT JOB_ID,DEPARTMENT_ID,TO_CHAR('Z') AS "DUMMY"
FROM EMPLOYEES
WHERE DEPARTMENT_ID=20 
UNION ALL
SELECT DISTINCT JOB_ID,DEPARTMENT_ID,TO_CHAR('Y') AS "DUMMY"
FROM EMPLOYEES
WHERE DEPARTMENT_ID=50 ;

REM --4TH QUESTION
SELECT EMPLOYEE_ID,JOB_ID
FROM EMPLOYEES
INTERSECT
SELECT EMPLOYEE_ID,JOB_ID
FROM JOB_HISTORY;

REM --5TH QUESTION
SELECT LAST_NAME,DEPARTMENT_ID,TO_CHAR(NULL)
FROM EMPLOYEES
UNION
SELECT TO_CHAR(NULL),DEPARTMENT_ID,DEPARTMENT_NAME
FROM DEPARTMENTS;


