REM --2ND QUESTION

DESC MY_EMPLOYEE;

REM --3RD QUESTION

INSERT INTO MY_EMPLOYEE
VALUES(1,'Petal','Ralph','rpatel',895);

REM --4TH QUESTION

INSERT INTO MY_EMPLOYEE(ID,LAST_NAME,FIRST_NAME,USERID,SALARY)
VALUES(2,'Dancs','Betty','Bdancs',860);


REM --5TH QUESTION
SELECT * FROM MY_EMPLOYEESSSSS


REM--6TH QUESTION

INSERT INTO MY_EMPLOYEE
VALUES(&ID,'&FNAME','&LNAME',
LOWER(SUBSTR('&FNAME',1,1)||SUBSTR('&LNAME',1,7)),&SAL);



REM --7TH QUESTION
INSERT INTO MY_EMPLOYEE
VALUES(&ID,'&FNAME','&LNAME',
LOWER(SUBSTR('&FNAME',1,1)||SUBSTR('&LNAME',1,7)),&SAL);
REM --8TH QUESTION

SELECT * FROM MY_EMPLOYEE;

REM --9TH QUESTION [TO MAKE DATA EDITIONS PERMANENT]

COMMIT;

REM --10TH QUESTION

UPDATE MY_EMPLOYEE
SET LAST_NAME='Drexler'
WHERE ID=3;

REM --11TH QUESTION

UPDATE MY_EMPLOYEE
SET SALARY =1000
WHERE SALARY<900;

REM -12TH QUSTION
SELECT LAST_NAME,SALARY
FROM MY_EMPLOYEE;


REM -- 13TH QUESTION

DELETE
FROM MY_EMPLOYEE
WHERE LAST_NAME='Dancs';

REM --14TH QUESTION
SELECT * FROM MY_EMPLOYEE;

REM --15TH QUESTION
COMMIT;

REM --16TH QUESTION

INSERT INTO MY_EMPLOYEE
VALUES(&ID,'&FNAME','&LNAME',
LOWER(SUBSTR('FNAME',1,1)||SUBSTR('LNAME',1,7)),&SALARY);

REM --17TH QUESTION

SELECT * FROM MY_EMPLOYEE;


REM --18TH QUSTION

SAVEPOINT STEP_19;

REM --19TH QUESTION

DELETE
FROM MY_EMPLOYEE;

REM --20TH QUESTION
SELECT * FROM MY_EMPLOYEE;

REM --21ST QUESTION
ROLLBACK STEP_19;
REM --22ND QUESTION
SELECT * FROM MY_EMPLOYEE;

REM --23RD QUESTION

COMMIT;
