REM --OTHER SCHEMA OBJECTS
REM -VIEWS

CREATE VIEW EMPV80
AS SELECT EMPLOYEE_ID,LAST_NAME,SALARY
FROM EMPLOYEES
WHERE DEPARTMENT_ID=80;

DESC EMPV80;


REM --CREATING A VIEW BY USING COLUMN ALIAS

CREATE VIEW SALVU50
AS SELECT EMPLOYEE_ID AS ID_NUMBER,LAST_NAME AS NAME,
SALARY*12 AS ANUUAL_SAL
FROM EMPLOYEES
WHERE DEPARTMENT_ID=50;

DESC SALVU50;

REM -- SELECTING DATA FROM VIW

SELECT * 
FROM SALVU50;

REM --MODIFYING THE VIEW

CREATE OR REPLACE VIEW EMPV80
(ID_NUMBER,NAME,SAL,DEPARTMENT_ID)
AS SELECT EMPLOYEE_ID,FIRST_NAME ||' '||lAST_NAME,
SALARY,DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID =80;

DESC EMPV80;
SELECT * FROM EMPV80;


REM -- CREATING A VIEW USING MULTPLE TABLE DATA
CREATE OR REPLACE VIEW DEPT_SUM_VU
(NAME,MINSAL,MAXSAL,AVGSAL)AS
SELECT D.DEPARTMENT_NAME, MIN(E.SALARY),MAX(E.SALARY),AVG(E.SALARY)
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
GROUP BY D.DEPARTMENT_ID;

REM --CHECK CONSTRAINT OPTION ON VIEW

CREATE OR REPLACE VIEW EMPVU20
AS SELECT *FROM EMPLOYEES
WHERE DEPARTMENT_ID=20
WITH CHECK OPTION CONSTRAINT EMPVU20_CK;



rem --read only option
CREATE OR REPLACE VIEW EMPVU10
(EMPLOYEE_NUMBER,EMPLOYEE_NAME,JOB_TITLE) AS
SELECT EMPLOYEE_ID,LAST_NAME,JOB_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID=10
WITH READ ONLY;

REM - DROPING A VIEW

DROP VIEW EMPVU10;

REM -- SEQUENCES
CREATE SEQUENCE DEPT_DEPTID_SEQ INCREMENT BY 10
START WITH 320
MAXVALUE 9999
NOCACHE
NOCYCLE;
INSERT INTO DEPARTMENTS(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
VALUES (DEPT_DEPTID_SEQ.NEXTVAL, 'Support', 1700);



REM -- SYNONYMS

CREATE SYNONYM DEPT_SEQ
FOR DEPT_DEPTID_SEQ;


REM -- TRIGGERS

