REM -- 1ST QUESTION


SELECT SYSDATE
FROM DUAL;


REM -- 2nd QUESTION

SELECT EMPLOYEE_ID, LAST_NAME, SALARY, SALARY+(SALARY*15.5/100) "New Salary"
FROM EMPLOYEES;

REM --4RD QUESTION

SELECT EMPLOYEE_ID,LAST_NAME,SALARY, SALARY+(SALARY*15.5/100) "New Salary",
(SALARY+SALARY*15.5/100)-SALARY "Increase"
FROM EMPLOYEES;


REM --5TH QUESTION

SELECT INITCAP(LAST_NAME) "Name", LENGTH(LAST_NAME) as "Length"
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'A%' OR
LAST_NAME LIKE 'J%' OR 
LAST_NAME LIKE 'M%'
ORDER BY LAST_NAME ;

REM -- 5TH QUESTION 2ND ANSWER

SELECT INITCAP(LAST_NAME) "Name", LENGTH(LAST_NAME) as "Length"
FROM EMPLOYEES
WHERE LAST_NAME LIKE ('&GIVEN_NAME%') 
ORDER BY LAST_NAME ;



REM --6TH QUESTION

SELECT LAST_NAME, ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE),0) AS "MONTHS_WORKED"
FROM EMPLOYEES
ORDER BY 2;
