REM -- 1ST QUESTION

SELECT LOCATION_ID,STREET_ADDRESS,CITY,STATE_PROVINCE,COUNTRY_NAME
FROM LOCATIONS
NATURAL JOIN COUNTRIES;

REM --2ND QUESTION

SELECT LAST_NAME,DEPARTMENT_ID,DEPARTMENT_NAME
FROM EMPLOYEES
JOIN DEPARTMENTS
USING (DEPARTMENT_ID);


REM-- 3RD QUESTION

SELECT E.LAST_NAME,E.JOB_ID,E.DEPARTMENT_ID,
D.DEPARTMENT_NAME
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN LOCATIONS L
ON(D.LOCATION_ID =L.LOCATION_ID)
WHERE L.CITY='Toronto';

REM --4TH QUESTION
SELECT E.LAST_NAME "Employee", E.EMPLOYEE_ID "EMP#",  
       M.LAST_NAME "Manager", M.EMPLOYEE_ID  "Mgr#" 
FROM   employees E 
JOIN  employees M
ON     (M.manager_id = E.employee_id);

REM --5TH QUESTION
SELECT E.LAST_NAME "Employee", E.EMPLOYEE_ID "EMP#",  
       M.LAST_NAME "Manager", M.EMPLOYEE_ID  "Mgr#" 
FROM   employees E 
LEFT OUTER JOIN employees M
ON     (M.manager_id = E.employee_id);

REM --6TH QUESTION

SELECT E.DEPARTMENT_ID "Department",E.LAST_NAME "Employee",
C.LAST_NAME "COLLEAGUE"
FROM EMPLOYEES E
JOIN EMPLOYEES C
ON(E.DEPARTMENT_ID =C.DEPARTMENT_ID)
WHERE E.EMPLOYEE_ID != C.EMPLOYEE_ID
ORDER BY E.DEPARTMENT_ID,E.LAST_NAME,C.LAST_NAME;


REM --7TH QUESTION

DESC JOB_GRADES

SELECT E.LAST_NAME,E.JOB_ID,D.DEPARYTMENT_NAME,E.SALARY, J.GRADE_LEVEL
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON(E.DEPARTMENT_ID=D.DEPARTMENT_ID)
JOIN JOB_GRADES J
ON(E.SALARY BETWEEN J.LOWEST_SAL AND J.HIGHEST_SAL);

REM --8TH QUESTION
SELECT E.LAST_NAME,E.HIRE_DATE
FROM EMPLOYEES E
JOIN EMPLOYEES D
ON(D.LAST_NAME ='Davies')
WHERE D.HIRE_DATE<E.HIRE_DATE;


REM --9TH QUESTION

SELECT E.LAST_NAME,E.HIRE_DATE,M.LAST_NAME, M.HIRE_DATE
FROM EMPLOYEES E
JOIN EMPLOYEES M
ON (E.MANAGER_ID =M.EMPLOYEE_ID)
WHERE E.HIRE_DATE<M.HIRE_DATE;

