REM --1ST QUESTION

CREATE OR REPLACE VIEW EMPLOYEES_VU AS
SELECT EMPLOYEE_ID,LAST_NAME EMPLOYEE,DEPARTMENT_ID
FROM EMPLOYEES;

REM --2ND QUESTION
SELECT * FROM EMPLOYEES_VU;

REM --3RD QUESTION

SELECT EMPLOYEE,DEPARTMENT_ID 
FROM EMPLOYEES_VU;


REM --4TH QUESTION

CREATE VIEW DEPT50
AS SELECT EMPLOYEE_ID EMPNO, LAST_NAME EMPLOYEE,
DEPARTMENT_ID DEPTNO
FROM EMPLOYEES
WHERE DEPARTMENT_ID=50
WITH CHECK OPTION CONSTRAINT EMP_DEPT_50;

REM --5TH QUESTION

DESC DEPT50;
SELECT * FROM DEPT50;

REM -- 6TH QUESTION

UPDATE DEPT50
SET DEPTNO=80
WHERE EMPLOYEE='Matos';

REM --7TH QUESTION

CREATE SEQUENCE DEPT_ID_SEQ
START WITH 200
INCREMENT BY 10
MAXVALUE 1000;

REM --8TH QUESTION
REM -- YESTERDAY [27/04/23] WE HAVE CREATED A TABLE CALLED DEPT50 AS A PART OF 
REM -- OUR DDL COMMNANDS,SO I HAVE USED THAT TABLE FOR THE
REM -- FOLLOWING OPERATIONS
INSERT INTO DEPT
VALUES(DEPT_ID_SEQ.NEXTVAL, 'Finance');

INSERT INTO DEPT
VALUES(DEPT_ID_SEQ.NEXTVAL,'Desk_Support');


REM --9TH QUESTION

CREATE INDEX EMP_DEPT_ID_INDEX ON DEPT(ID);
REM --10TH QUESTION

CREATE SYNONYM EMP
FOR EMPLOYEES;