REM -- CHARECTER FUNCTIONS [CASE CONVERSTION]
REM -- DUAL IS A DUMMY TABLE IN SQL

SELECT LOWER('SQL COURSE')
FROM DUAL;

SELECT UPPER('sql course')
FROM DUAL;


SELECT INITCAP('KOUSIL LAKKAPRAGADA')
FROM DUAL;


SELECT EMPLOYEE_ID,LAST_NAME,DEPARTMENT_ID
FROM EMPLOYEES
WHERE LOWER(LAST_NAME)='higgins';


REM -- CHARACTER MANIPULATION FUNCTIONS

SELECT LAST_NAME, CONCAT('JOB CATEGOTY IS ',JOB_ID)
FROM EMPLOYEES
WHERE SUBSTR(JOB_ID,4,3) ='REP';

SELECT  EMPLOYEE_ID, CONCAT(FIRST_NAME,LAST_NAME) AS NAME,
LENGTH(LAST_NAME),INSTR(LAST_NAME,'a')"CONTAINS 'a'?"
FROM EMPLOYEES
WHERE SUBSTR(LAST_NAME,-1,1)='n';


REM-- NESTED FUNCTIONS

SELECT LAST_NAME, UPPER(CONCAT(SUBSTR(LAST_NAME,1,8),'_US'))
FROM EMPLOYEES
WHERE DEPARTMENT_ID=60;


REM -- USING NUMRIC FUNCTIONS

SELECT ROUND(45.923,2),ROUND(45.923,0)
FROM DUAL;

SELECT TRUNC(45.923,2),TRUNC(45.923,0)
FROM DUAL;

SELECT LAST_NAME, SALARY,MOD(SALARY,5000)
FROM EMPLOYEES
WHERE JOB_ID='SA_REP';

SELECT EMPLOYEE_ID AS "EVEN NUMBER", LAST_NAME
FROM EMPLOYEES
WHERE MOD(EMPLOYEE_ID,2)=0;


SELECT LAST_NAME, HIRE_DATE
FROM EMPLOYEES
WHERE HIRE_DATE < '01-FEB-2008';


SELECT SYSDATE
FROM DUAL;

SELECT SESSIONTIMEZONE FROM
DUAL;


SELECT LAST_NAME, (SYSDATE -HIRE_DATE)/7 AS WEEKS
FROM EMPLOYEES
WHERE DEPARTMENT_ID=90;


REM -- DATE MANIPULATION FUNCTIONS

