REM --1ST QUESTION

CREATE TABLE DEPT (ID NUMBER(7) PRIMARY KEY,NAME VARCHAR2(25));


DESC DEPT;

REM --2ND QUESTION

INSERT INTO DEPT
SELECT DEPARTMENT_ID,DEPARTMENT_NAME
FROM DEPARTMENTS;


REM --3RD QUESTION

CREATE TABLE EMP
(ID NUMBER(7),LAST_NAME VARCHAR2(25),FIRST_NAME VARCHAR2(25),DEPT_ID NUMBER(7),
  CONSTRAINT FK_DEPT_ID FOREIGN KEY (DEPT_ID) REFERENCES DEPT(ID);

REM --4TH QUESTION
CREATE TABLE EMPLOYEES2 AS
SELECT EMPLOYEE_ID AS ID ,FIRST_NAME,LAST_NAME,SALARY,DEPARTMENT_ID AS DEPT_ID FROM EMPLOYEES;

REM --5TH QUESTION
DROP TABLE EMPLOYEES2;