REM-- USING WHERE CLAUSE

SELECT
    employee_id,
    last_name,
    job_id,
    department_id
FROM
    employees
WHERE
    department_id = 90;

REM-- UISNG CHARACTER AND DATE LIETRALS

SELECT
    last_name,
    job_id,
    department_id
FROM
    employees
WHERE
    last_name = 'Whalen';

SELECT
    last_name
FROM
    employees
WHERE
    hire_date = '17-OCT-03';
    
    
REM -- USING COMPARRSION OPERATORS

SELECT LAST_NAME, SALARY
FROM EMPLOYEES
WHERE SALARY<=3000;


SELECT * 
FROM EMPLOYEES
WHERE LAST_NAME='Abel';


SELECT LAST_NAME,SALARY
FROM EMPLOYEES
WHERE SALARY BETWEEN 2500 AND 3500;

SELECT EMPLOYEE_ID,LAST_NAME,SALARY,MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID IN(100,101,201);


SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'S%';


SELECT LAST_NAME
FROM EMPLOYEES
WHERE LAST_NAME LIKE '_O%';


SELECT LAST_NAME,MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS  NULL;

SELECT LAST_NAME,MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL;


select EMPLOYEE_ID,LAST_NAME,JOB_ID
FROM EMPLOYEES
WHERE SALARY >=10000 AND
JOB_ID LIKE '%MAN%';

select EMPLOYEE_ID,LAST_NAME,JOB_ID
FROM EMPLOYEES
WHERE SALARY >=10000 OR
JOB_ID LIKE '%MAN%';


SELECT LAST_NAME, JOB_ID
FROM EMPLOYEES
WHERE JOB_ID NOT IN ('IT_PROG','ST_CLERK','SA_REP');

REM -- OPERATOR PRESEDENCE

SELECT LAST_NAME,JOB_ID,SALARY
FROM EMPLOYEES
WHERE  JOB_ID='SA_REP' OR JOB_ID= 'AD_PRES' AND SALARY>15000 ;

SELECT LAST_NAME,JOB_ID,SALARY
FROM EMPLOYEES
WHERE  (JOB_ID='SA_REP' OR JOB_ID= 'AD_PRES') AND SALARY>15000;


REM --ORDER BY CLASS

SELECT LAST_NAME,JOB_ID,DEPARTMENT_ID,HIRE_DATE
FROM EMPLOYEES
ORDER BY HIRE_DATE;

SELECT LAST_NAME,JOB_ID,DEPARTMENT_ID,HIRE_DATE
FROM EMPLOYEES
ORDER BY HIRE_DATE DESC;


SELECT EMPLOYEE_ID ,LAST_NAME, SALARY *12  ANNSAL
FROM EMPLOYEES
ORDER BY ANNSAL;


REM -- SORT BY NUMIRIC POSITION

SELECT LAST_NAME, JOB_ID,DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
ORDER BY 3;


REM -- SORT BY MULTIPLE COLOUMNS
SELECT LAST_NAME, JOB_ID,DEPARTMENT_ID, HIRE_DATE
FROM EMPLOYEES
ORDER BY DEPARTMENT_ID,SALARY DESC;



REM -- SUBSTITION VARIABLES


SELECT EMPLOYEE_ID,FIRST_NAME, LAST_NAME,DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID=&EMP_NO AND SALARY>&gIVEN_SALARY;


SELECT EMPLOYEE_ID,FIRST_NAME, LAST_NAME,DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID=&EMP_NO AND FIRST_NAME LIKE '&GIVEN_NAME';

SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY, &GIVEN_COL
FROM EMPLOYEES
WHERE EMPLOYEE_ID=&GIVEN_EMP_ID
ORDER BY &GIVEN_ORDERBY;

REM -- USING DOUBLE AMPERSED

SELECT EMPLOYEE_ID,LAST_NAME,JOB_ID,&&COL_NAME
FROM EMPLOYEES
ORDER BY &COL_NAME;



REM -- DEFINE ADN UN DEFINE

DEFINE EMP_NO=200

SELECT EMPLOYEE_ID,LAST_NAME,SALARY,DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID =&EMP_NO;
UNDEFINE EMP_NO


REM --VERIFY ON

SET VERIFY ON

SELECT EMPLOYEE_ID,LAST_NAME,SALARY,DEPARTMENT_ID
FROM EMPLOYEES
WHERE EMPLOYEE_ID =&EMP_NO;











